"""Database di domande quiz in italiano."""

DOMANDE_ITALIANE = [
    # Geografia
    {"domanda": "Qual è la capitale dell'Italia?", "opzioni": {"a": "Milano", "b": "Roma", "c": "Napoli", "d": "Torino"}, "risposta": "b", "categoria": "Geografia", "difficolta": "Facile"},
    {"domanda": "Qual è il fiume più lungo d'Italia?", "opzioni": {"a": "Arno", "b": "Tevere", "c": "Po", "d": "Adige"}, "risposta": "c", "categoria": "Geografia", "difficolta": "Facile"},
    {"domanda": "In quale regione si trova Venezia?", "opzioni": {"a": "Lombardia", "b": "Veneto", "c": "Emilia-Romagna", "d": "Friuli-Venezia Giulia"}, "risposta": "b", "categoria": "Geografia", "difficolta": "Facile"},
    {"domanda": "Qual è la montagna più alta d'Italia?", "opzioni": {"a": "Gran Sasso", "b": "Monte Bianco", "c": "Marmolada", "d": "Etna"}, "risposta": "b", "categoria": "Geografia", "difficolta": "Media"},
    {"domanda": "Qual è la capitale della Francia?", "opzioni": {"a": "Lione", "b": "Marsiglia", "c": "Parigi", "d": "Nizza"}, "risposta": "c", "categoria": "Geografia", "difficolta": "Facile"},
    {"domanda": "Quale oceano bagna la costa occidentale dell'Italia?", "opzioni": {"a": "Atlantico", "b": "Pacifico", "c": "Mediterraneo", "d": "Indiano"}, "risposta": "c", "categoria": "Geografia", "difficolta": "Facile"},
    {"domanda": "Qual è la capitale della Spagna?", "opzioni": {"a": "Barcellona", "b": "Siviglia", "c": "Madrid", "d": "Valencia"}, "risposta": "c", "categoria": "Geografia", "difficolta": "Facile"},
    {"domanda": "In quale continente si trova il Brasile?", "opzioni": {"a": "Africa", "b": "Asia", "c": "America", "d": "Oceania"}, "risposta": "c", "categoria": "Geografia", "difficolta": "Facile"},
    {"domanda": "Qual è il lago più grande d'Italia?", "opzioni": {"a": "Lago di Como", "b": "Lago di Garda", "c": "Lago Maggiore", "d": "Lago di Bolsena"}, "risposta": "b", "categoria": "Geografia", "difficolta": "Media"},
    {"domanda": "Quale stretto separa la Sicilia dalla Calabria?", "opzioni": {"a": "Stretto di Gibilterra", "b": "Stretto di Messina", "c": "Stretto di Otranto", "d": "Canale della Mancia"}, "risposta": "b", "categoria": "Geografia", "difficolta": "Media"},
    # Storia
    {"domanda": "In quale anno è caduto il muro di Berlino?", "opzioni": {"a": "1987", "b": "1989", "c": "1991", "d": "1993"}, "risposta": "b", "categoria": "Storia", "difficolta": "Media"},
    {"domanda": "Chi fu il primo imperatore romano?", "opzioni": {"a": "Giulio Cesare", "b": "Nerone", "c": "Augusto", "d": "Traiano"}, "risposta": "c", "categoria": "Storia", "difficolta": "Media"},
    {"domanda": "In quale anno l'Italia è diventata una Repubblica?", "opzioni": {"a": "1943", "b": "1945", "c": "1946", "d": "1948"}, "risposta": "c", "categoria": "Storia", "difficolta": "Media"},
    {"domanda": "Chi scoprì l'America nel 1492?", "opzioni": {"a": "Marco Polo", "b": "Amerigo Vespucci", "c": "Cristoforo Colombo", "d": "Fernando Magellano"}, "risposta": "c", "categoria": "Storia", "difficolta": "Facile"},
    {"domanda": "In quale secolo è avvenuta la Rivoluzione francese?", "opzioni": {"a": "XV", "b": "XVI", "c": "XVII", "d": "XVIII"}, "risposta": "d", "categoria": "Storia", "difficolta": "Media"},
    {"domanda": "Chi era il leader del fascismo italiano?", "opzioni": {"a": "Garibaldi", "b": "Mussolini", "c": "Cavour", "d": "D'Annunzio"}, "risposta": "b", "categoria": "Storia", "difficolta": "Facile"},
    {"domanda": "In quale anno è iniziata la Prima guerra mondiale?", "opzioni": {"a": "1912", "b": "1914", "c": "1916", "d": "1918"}, "risposta": "b", "categoria": "Storia", "difficolta": "Media"},
    {"domanda": "Chi fu l'ultimo re d'Italia?", "opzioni": {"a": "Vittorio Emanuele II", "b": "Umberto I", "c": "Vittorio Emanuele III", "d": "Umberto II"}, "risposta": "d", "categoria": "Storia", "difficolta": "Difficile"},
    # Scienza
    {"domanda": "Qual è la formula chimica dell'acqua?", "opzioni": {"a": "CO2", "b": "H2O", "c": "O2", "d": "NaCl"}, "risposta": "b", "categoria": "Scienza", "difficolta": "Facile"},
    {"domanda": "Qual è il pianeta più grande del sistema solare?", "opzioni": {"a": "Saturno", "b": "Giove", "c": "Nettuno", "d": "Urano"}, "risposta": "b", "categoria": "Scienza", "difficolta": "Facile"},
    {"domanda": "Quanti pianeti ci sono nel sistema solare?", "opzioni": {"a": "7", "b": "8", "c": "9", "d": "10"}, "risposta": "b", "categoria": "Scienza", "difficolta": "Facile"},
    {"domanda": "Qual è la velocità della luce nel vuoto (circa)?", "opzioni": {"a": "300.000 km/s", "b": "30.000 km/s", "c": "3.000 km/s", "d": "150.000 km/s"}, "risposta": "a", "categoria": "Scienza", "difficolta": "Difficile"},
    {"domanda": "Quale organo pompa il sangue nel corpo umano?", "opzioni": {"a": "Polmoni", "b": "Fegato", "c": "Cuore", "d": "Reni"}, "risposta": "c", "categoria": "Scienza", "difficolta": "Facile"},
    {"domanda": "Qual è il simbolo chimico dell'oro?", "opzioni": {"a": "Ag", "b": "Fe", "c": "Au", "d": "Cu"}, "risposta": "c", "categoria": "Scienza", "difficolta": "Media"},
    {"domanda": "Quanti cromosomi ha una cellula umana normale?", "opzioni": {"a": "23", "b": "46", "c": "48", "d": "64"}, "risposta": "b", "categoria": "Scienza", "difficolta": "Difficile"},
    {"domanda": "Quale gas respirano principalmente le piante di notte?", "opzioni": {"a": "Ossigeno", "b": "Azoto", "c": "Anidride carbonica", "d": "Idrogeno"}, "risposta": "c", "categoria": "Scienza", "difficolta": "Media"},
    {"domanda": "Chi formulò la teoria della relatività?", "opzioni": {"a": "Newton", "b": "Galileo", "c": "Einstein", "d": "Hawking"}, "risposta": "c", "categoria": "Scienza", "difficolta": "Facile"},
    {"domanda": "A quale temperatura l'acqua bolle a livello del mare?", "opzioni": {"a": "90°C", "b": "100°C", "c": "110°C", "d": "80°C"}, "risposta": "b", "categoria": "Scienza", "difficolta": "Facile"},
    # Cultura generale
    {"domanda": "Quanti continenti ci sono sulla Terra?", "opzioni": {"a": "5", "b": "6", "c": "7", "d": "8"}, "risposta": "c", "categoria": "Cultura generale", "difficolta": "Facile"},
    {"domanda": "Quante ore ha un giorno?", "opzioni": {"a": "12", "b": "24", "c": "48", "d": "60"}, "risposta": "b", "categoria": "Cultura generale", "difficolta": "Facile"},
    {"domanda": "Quanti minuti ha un'ora?", "opzioni": {"a": "30", "b": "45", "c": "60", "d": "100"}, "risposta": "c", "categoria": "Cultura generale", "difficolta": "Facile"},
    {"domanda": "Quanti lati ha un triangolo?", "opzioni": {"a": "2", "b": "3", "c": "4", "d": "5"}, "risposta": "b", "categoria": "Cultura generale", "difficolta": "Facile"},
    {"domanda": "Quale linguaggio usiamo in questo progetto?", "opzioni": {"a": "Java", "b": "C++", "c": "Python", "d": "JavaScript"}, "risposta": "c", "categoria": "Cultura generale", "difficolta": "Facile"},
    {"domanda": "Quanti giorni ha un anno bisestile?", "opzioni": {"a": "365", "b": "366", "c": "364", "d": "367"}, "risposta": "b", "categoria": "Cultura generale", "difficolta": "Facile"},
    {"domanda": "Qual è la moneta dell'Unione Europea?", "opzioni": {"a": "Dollaro", "b": "Sterlina", "c": "Euro", "d": "Franco"}, "risposta": "c", "categoria": "Cultura generale", "difficolta": "Facile"},
    {"domanda": "Quante lettere ha l'alfabeto italiano?", "opzioni": {"a": "21", "b": "22", "c": "26", "d": "28"}, "risposta": "a", "categoria": "Cultura generale", "difficolta": "Media"},
    # Arte e letteratura
    {"domanda": "Chi ha dipinto la Gioconda?", "opzioni": {"a": "Michelangelo", "b": "Raffaello", "c": "Leonardo da Vinci", "d": "Donatello"}, "risposta": "c", "categoria": "Arte e letteratura", "difficolta": "Facile"},
    {"domanda": "Chi scrisse 'I Promessi Sposi'?", "opzioni": {"a": "Dante", "b": "Manzoni", "c": "Leopardi", "d": "Pirandello"}, "risposta": "b", "categoria": "Arte e letteratura", "difficolta": "Facile"},
    {"domanda": "Chi scrisse la 'Divina Commedia'?", "opzioni": {"a": "Petrarca", "b": "Boccaccio", "c": "Dante Alighieri", "d": "Ariosto"}, "risposta": "c", "categoria": "Arte e letteratura", "difficolta": "Facile"},
    {"domanda": "Chi dipinse la Cappella Sistina?", "opzioni": {"a": "Raffaello", "b": "Botticelli", "c": "Michelangelo", "d": "Caravaggio"}, "risposta": "c", "categoria": "Arte e letteratura", "difficolta": "Facile"},
    {"domanda": "In quale città si trova il Colosseo?", "opzioni": {"a": "Napoli", "b": "Roma", "c": "Firenze", "d": "Milano"}, "risposta": "b", "categoria": "Arte e letteratura", "difficolta": "Facile"},
    {"domanda": "Chi compose le 'Quattro Stagioni'?", "opzioni": {"a": "Mozart", "b": "Beethoven", "c": "Vivaldi", "d": "Bach"}, "risposta": "c", "categoria": "Arte e letteratura", "difficolta": "Media"},
    {"domanda": "Chi scrisse 'Il nome della rosa'?", "opzioni": {"a": "Calvino", "b": "Eco", "c": "Moravia", "d": "Sciascia"}, "risposta": "b", "categoria": "Arte e letteratura", "difficolta": "Media"},
    # Sport
    {"domanda": "In quale sport si usa un pallone ovale?", "opzioni": {"a": "Calcio", "b": "Basket", "c": "Rugby", "d": "Tennis"}, "risposta": "c", "categoria": "Sport", "difficolta": "Facile"},
    {"domanda": "Quanti giocatori ha una squadra di calcio in campo?", "opzioni": {"a": "9", "b": "10", "c": "11", "d": "12"}, "risposta": "c", "categoria": "Sport", "difficolta": "Facile"},
    {"domanda": "Ogni quanti anni si svolgono le Olimpiadi estive?", "opzioni": {"a": "2", "b": "3", "c": "4", "d": "5"}, "risposta": "c", "categoria": "Sport", "difficolta": "Facile"},
    {"domanda": "In quale sport si usa la racchetta e la pallina gialla?", "opzioni": {"a": "Golf", "b": "Tennis", "c": "Pallavolo", "d": "Baseball"}, "risposta": "b", "categoria": "Sport", "difficolta": "Facile"},
    {"domanda": "Quale paese ha vinto i Mondiali di calcio 2006?", "opzioni": {"a": "Brasile", "b": "Germania", "c": "Italia", "d": "Francia"}, "risposta": "c", "categoria": "Sport", "difficolta": "Facile"},
    {"domanda": "Quanti set si giocano al massimo in una partita di tennis maschile al Grande Slam?", "opzioni": {"a": "3", "b": "4", "c": "5", "d": "7"}, "risposta": "c", "categoria": "Sport", "difficolta": "Media"},
    # Intrattenimento
    {"domanda": "Quale studio ha creato Super Mario?", "opzioni": {"a": "Sega", "b": "Sony", "c": "Nintendo", "d": "Microsoft"}, "risposta": "c", "categoria": "Intrattenimento", "difficolta": "Facile"},
    {"domanda": "Chi interpretò Jack in 'Titanic'?", "opzioni": {"a": "Brad Pitt", "b": "Leonardo DiCaprio", "c": "Tom Cruise", "d": "Johnny Depp"}, "risposta": "b", "categoria": "Intrattenimento", "difficolta": "Facile"},
    {"domanda": "In quale città si svolge il Festival di Sanremo?", "opzioni": {"a": "Roma", "b": "Milano", "c": "Sanremo", "d": "Torino"}, "risposta": "c", "categoria": "Intrattenimento", "difficolta": "Facile"},
    {"domanda": "Quale saga cinematografica include il personaggio Harry Potter?", "opzioni": {"a": "Il Signore degli Anelli", "b": "Star Wars", "c": "Harry Potter", "d": "Marvel"}, "risposta": "c", "categoria": "Intrattenimento", "difficolta": "Facile"},
    {"domanda": "Chi è noto come il 'Re del Pop'?", "opzioni": {"a": "Elvis Presley", "b": "Michael Jackson", "c": "Prince", "d": "Madonna"}, "risposta": "b", "categoria": "Intrattenimento", "difficolta": "Facile"},
    # Italia
    {"domanda": "Qual è il simbolo della Repubblica Italiana?", "opzioni": {"a": "Aquila", "b": "Stella", "c": "Cavallo", "d": "Leone"}, "risposta": "b", "categoria": "Italia", "difficolta": "Media"},
    {"domanda": "Quante regioni ha l'Italia?", "opzioni": {"a": "18", "b": "20", "c": "22", "d": "24"}, "risposta": "b", "categoria": "Italia", "difficolta": "Media"},
    {"domanda": "Qual è la lingua ufficiale dell'Italia?", "opzioni": {"a": "Latino", "b": "Italiano", "c": "Francese", "d": "Tedesco"}, "risposta": "b", "categoria": "Italia", "difficolta": "Facile"},
    {"domanda": "In quale città si trova la Torre di Pisa?", "opzioni": {"a": "Firenze", "b": "Pisa", "c": "Siena", "d": "Lucca"}, "risposta": "b", "categoria": "Italia", "difficolta": "Facile"},
    {"domanda": "Chi compose l'inno di Mameli?", "opzioni": {"a": "Verdi", "b": "Mameli", "c": "Puccini", "d": "Rossini"}, "risposta": "b", "categoria": "Italia", "difficolta": "Media"},
    {"domanda": "Qual è il vulcano attivo più famoso d'Italia?", "opzioni": {"a": "Vesuvio", "b": "Stromboli", "c": "Etna", "d": "Vulcano"}, "risposta": "c", "categoria": "Italia", "difficolta": "Facile"},
    {"domanda": "Quale città italiana è famosa per il Carnevale con le maschere?", "opzioni": {"a": "Roma", "b": "Venezia", "c": "Napoli", "d": "Palermo"}, "risposta": "b", "categoria": "Italia", "difficolta": "Facile"},
    {"domanda": "Chi fu l'eroe dei Mille?", "opzioni": {"a": "Mazzini", "b": "Garibaldi", "c": "Cavour", "d": "Vittorio Emanuele II"}, "risposta": "b", "categoria": "Italia", "difficolta": "Media"},
    # Matematica
    {"domanda": "Quanto fa 7 × 8?", "opzioni": {"a": "54", "b": "56", "c": "58", "d": "64"}, "risposta": "b", "categoria": "Matematica", "difficolta": "Facile"},
    {"domanda": "Quanti gradi ha un angolo retto?", "opzioni": {"a": "45", "b": "90", "c": "180", "d": "360"}, "risposta": "b", "categoria": "Matematica", "difficolta": "Facile"},
    {"domanda": "Qual è il valore di π approssimato a due decimali?", "opzioni": {"a": "3,12", "b": "3,14", "c": "3,16", "d": "3,41"}, "risposta": "b", "categoria": "Matematica", "difficolta": "Media"},
    {"domanda": "Quanto fa 15% di 200?", "opzioni": {"a": "20", "b": "25", "c": "30", "d": "35"}, "risposta": "c", "categoria": "Matematica", "difficolta": "Media"},
    {"domanda": "Quanti lati ha un esagono?", "opzioni": {"a": "5", "b": "6", "c": "7", "d": "8"}, "risposta": "b", "categoria": "Matematica", "difficolta": "Facile"},
    # Animali e natura
    {"domanda": "Qual è l'animale più veloce sulla terra?", "opzioni": {"a": "Leone", "b": "Ghepardo", "c": "Antilope", "d": "Cavallo"}, "risposta": "b", "categoria": "Natura", "difficolta": "Facile"},
    {"domanda": "Quale mammifero marino è il più grande?", "opzioni": {"a": "Squalo balena", "b": "Balena blu", "c": "Orca", "d": "Delfino"}, "risposta": "b", "categoria": "Natura", "difficolta": "Media"},
    {"domanda": "Da cosa si nutrono principalmente le api?", "opzioni": {"a": "Foglie", "b": "Nettare e polline", "c": "Piccoli insetti", "d": "Semi"}, "risposta": "b", "categoria": "Natura", "difficolta": "Facile"},
    {"domanda": "Quale albero produce le olive?", "opzioni": {"a": "Quercia", "b": "Olivo", "c": "Pino", "d": "Betulla"}, "risposta": "b", "categoria": "Natura", "difficolta": "Facile"},
    {"domanda": "Quanti stomaci ha una mucca?", "opzioni": {"a": "1", "b": "2", "c": "3", "d": "4"}, "risposta": "d", "categoria": "Natura", "difficolta": "Difficile"},
    # Domande difficili aggiuntive
    {"domanda": "In quale anno fu firmato il Trattato di Roma, che istituì la CEE?", "opzioni": {"a": "1945", "b": "1957", "c": "1969", "d": "1985"}, "risposta": "b", "categoria": "Storia", "difficolta": "Difficile"},
    {"domanda": "Chi scoprì la penicillina nel 1928?", "opzioni": {"a": "Pasteur", "b": "Fleming", "c": "Koch", "d": "Jenner"}, "risposta": "b", "categoria": "Scienza", "difficolta": "Difficile"},
    {"domanda": "Qual è la capitale dell'Australia?", "opzioni": {"a": "Sydney", "b": "Melbourne", "c": "Canberra", "d": "Perth"}, "risposta": "c", "categoria": "Geografia", "difficolta": "Difficile"},
    {"domanda": "Chi scrisse 'Se questo è un uomo'?", "opzioni": {"a": "Calvino", "b": "Levi", "c": "Pavese", "d": "Montale"}, "risposta": "b", "categoria": "Arte e letteratura", "difficolta": "Difficile"},
    {"domanda": "Quale elemento chimico ha numero atomico 79?", "opzioni": {"a": "Argento", "b": "Ferro", "c": "Oro", "d": "Platino"}, "risposta": "c", "categoria": "Scienza", "difficolta": "Difficile"},
    {"domanda": "In quale anno l'Italia vinse il suo primo Mondiale di calcio?", "opzioni": {"a": "1934", "b": "1938", "c": "1982", "d": "2006"}, "risposta": "a", "categoria": "Sport", "difficolta": "Difficile"},
    {"domanda": "Chi fu il primo presidente della Repubblica Italiana?", "opzioni": {"a": "De Gasperi", "b": "Einaudi", "c": "Gronchi", "d": "Segni"}, "risposta": "b", "categoria": "Italia", "difficolta": "Difficile"},
    {"domanda": "Quale filosofo greco fu maestro di Alessandro Magno?", "opzioni": {"a": "Platone", "b": "Socrate", "c": "Aristotele", "d": "Epicuro"}, "risposta": "c", "categoria": "Storia", "difficolta": "Difficile"},
    {"domanda": "Quanto fa la radice quadrata di 144?", "opzioni": {"a": "10", "b": "11", "c": "12", "d": "14"}, "risposta": "c", "categoria": "Matematica", "difficolta": "Difficile"},
    {"domanda": "Quale organello cellulare produce l'ATP?", "opzioni": {"a": "Nucleo", "b": "Ribosoma", "c": "Mitocondrio", "d": "Lisosoma"}, "risposta": "c", "categoria": "Scienza", "difficolta": "Difficile"},
    # Domande aggiuntive Media
    {"domanda": "Qual è la capitale della Norvegia?", "opzioni": {"a": "Stoccolma", "b": "Oslo", "c": "Copenaghen", "d": "Reykjavik"}, "risposta": "b", "categoria": "Geografia", "difficolta": "Media"},
    {"domanda": "Quanti muscoli ha il corpo umano?", "opzioni": {"a": "206", "b": "316", "c": "400", "d": "500"}, "risposta": "c", "categoria": "Scienza", "difficolta": "Media"},
    {"domanda": "Chi scrisse 'Orgoglio e Pregiudizio'?", "opzioni": {"a": "Jane Austen", "b": "Charlotte Brontë", "c": "George Eliot", "d": "Emily Dickinson"}, "risposta": "a", "categoria": "Arte e letteratura", "difficolta": "Media"},
    {"domanda": "In quale anno fu costruita la Torre Eiffel?", "opzioni": {"a": "1887", "b": "1889", "c": "1891", "d": "1893"}, "risposta": "b", "categoria": "Storia", "difficolta": "Media"},
    {"domanda": "Quanti stati ha gli USA?", "opzioni": {"a": "45", "b": "48", "c": "50", "d": "52"}, "risposta": "c", "categoria": "Geografia", "difficolta": "Media"},
    {"domanda": "Chi dipinse 'La Notte Stellata'?", "opzioni": {"a": "Monet", "b": "Van Gogh", "c": "Cézanne", "d": "Matisse"}, "risposta": "b", "categoria": "Arte e letteratura", "difficolta": "Media"},
    {"domanda": "Qual è l'elemento più leggero della tavola periodica?", "opzioni": {"a": "Elio", "b": "Litio", "c": "Idrogeno", "d": "Neon"}, "risposta": "c", "categoria": "Scienza", "difficolta": "Media"},
    {"domanda": "In quale continente si trova l'Egitto?", "opzioni": {"a": "Asia", "b": "Africa", "c": "Europa", "d": "Oceania"}, "risposta": "b", "categoria": "Geografia", "difficolta": "Media"},
    {"domanda": "Quanti film compongono la trilogia originale di Star Wars?", "opzioni": {"a": "2", "b": "3", "c": "4", "d": "5"}, "risposta": "b", "categoria": "Intrattenimento", "difficolta": "Media"},
    {"domanda": "Chi fu il primo uomo sulla Luna?", "opzioni": {"a": "Buzz Aldrin", "b": "Neil Armstrong", "c": "Michael Collins", "d": "Yuri Gagarin"}, "risposta": "b", "categoria": "Storia", "difficolta": "Media"},
    {"domanda": "Qual è la velocità del suono nell'aria (circa)?", "opzioni": {"a": "300 m/s", "b": "340 m/s", "c": "400 m/s", "d": "500 m/s"}, "risposta": "b", "categoria": "Scienza", "difficolta": "Media"},
    {"domanda": "In quale città si trova il Museo del Prado?", "opzioni": {"a": "Barcellona", "b": "Siviglia", "c": "Madrid", "d": "Valencia"}, "risposta": "c", "categoria": "Arte e letteratura", "difficolta": "Media"},
    {"domanda": "Quanti lati ha un quadrato?", "opzioni": {"a": "3", "b": "4", "c": "5", "d": "6"}, "risposta": "b", "categoria": "Matematica", "difficolta": "Media"},
    {"domanda": "Quale poeta scrisse 'La Struttura della Visione'?", "opzioni": {"a": "Petrarca", "b": "Montale", "c": "Quasimodo", "d": "Giacco"}, "risposta": "b", "categoria": "Arte e letteratura", "difficolta": "Media"},
    {"domanda": "Qual è l'animale terrestre più pesante?", "opzioni": {"a": "Ippopotamo", "b": "Rinoceronte", "c": "Elefante", "d": "Giraffa"}, "risposta": "c", "categoria": "Natura", "difficolta": "Media"},
    {"domanda": "In quale anno scoppiò la Rivoluzione russa?", "opzioni": {"a": "1905", "b": "1917", "c": "1925", "d": "1935"}, "risposta": "b", "categoria": "Storia", "difficolta": "Media"},
    {"domanda": "Qual è il fiume più lungo del mondo?", "opzioni": {"a": "Nilo", "b": "Amazzoni", "c": "Yangtze", "d": "Mississippi"}, "risposta": "a", "categoria": "Geografia", "difficolta": "Media"},
    {"domanda": "Chi scrisse la Bibbia nel Nuovo Testamento?", "opzioni": {"a": "Un autore", "b": "Più autori", "c": "Mosè", "d": "Gesù"}, "risposta": "b", "categoria": "Storia", "difficolta": "Media"},
    # Domande aggiuntive Difficile
    {"domanda": "Chi vinse il Premio Nobel per la Fisica nel 1921?", "opzioni": {"a": "Max Planck", "b": "Albert Einstein", "c": "Niels Bohr", "d": "Erwin Schrödinger"}, "risposta": "b", "categoria": "Scienza", "difficolta": "Difficile"},
    {"domanda": "In quale anno terminò la Guerra dei Trent'anni?", "opzioni": {"a": "1645", "b": "1648", "c": "1652", "d": "1659"}, "risposta": "b", "categoria": "Storia", "difficolta": "Difficile"},
    {"domanda": "Qual è la capitale della Bhutan?", "opzioni": {"a": "Thimphu", "b": "Bumthang", "c": "Paro", "d": "Punakha"}, "risposta": "a", "categoria": "Geografia", "difficolta": "Difficile"},
    {"domanda": "Chi ha dipinto 'Il Giardino delle Delizie'?", "opzioni": {"a": "Bosch", "b": "Dalí", "c": "Magritte", "d": "Ernst"}, "risposta": "a", "categoria": "Arte e letteratura", "difficolta": "Difficile"},
    {"domanda": "Qual è il numero atomico del Carbonio?", "opzioni": {"a": "5", "b": "6", "c": "7", "d": "8"}, "risposta": "b", "categoria": "Scienza", "difficolta": "Difficile"},
    {"domanda": "Chi era il leader politico dell'URSS durante la Seconda guerra mondiale?", "opzioni": {"a": "Lenin", "b": "Trotsky", "c": "Stalin", "d": "Krusciov"}, "risposta": "c", "categoria": "Storia", "difficolta": "Difficile"},
    {"domanda": "In quale paese si trova il Monte Aconcagua?", "opzioni": {"a": "Bolivia", "b": "Cile", "c": "Argentina", "d": "Perù"}, "risposta": "c", "categoria": "Geografia", "difficolta": "Difficile"},
    {"domanda": "Chi scrisse 'Cent'anni di solitudine'?", "opzioni": {"a": "Jorge Luis Borges", "b": "Gabriel García Márquez", "c": "Pablo Neruda", "d": "Carlos Fuentes"}, "risposta": "b", "categoria": "Arte e letteratura", "difficolta": "Difficile"},
    {"domanda": "Quale legge descrive la relazione tra pressione e volume di un gas?", "opzioni": {"a": "Legge di Charles", "b": "Legge di Boyle", "c": "Legge di Gay-Lussac", "d": "Legge di Dalton"}, "risposta": "b", "categoria": "Scienza", "difficolta": "Difficile"},
    {"domanda": "In quale battaglia Napoleone fu definitivamente sconfitto?", "opzioni": {"a": "Waterloo", "b": "Austerlitz", "c": "Borodino", "d": "Lipsia"}, "risposta": "a", "categoria": "Storia", "difficolta": "Difficile"},
    {"domanda": "Qual è la capitale dell'Islanda?", "opzioni": {"a": "Reykjavik", "b": "Akureyri", "c": "Hafnarfjörður", "d": "Kópavogur"}, "risposta": "a", "categoria": "Geografia", "difficolta": "Difficile"},
    {"domanda": "Chi ha composto l'opera 'La Bohème'?", "opzioni": {"a": "Verdi", "b": "Puccini", "c": "Rossini", "d": "Donizetti"}, "risposta": "b", "categoria": "Arte e letteratura", "difficolta": "Difficile"},
    {"domanda": "Quale particella subatomica ha carica negativa?", "opzioni": {"a": "Protone", "b": "Neutrone", "c": "Elettrone", "d": "Positrone"}, "risposta": "c", "categoria": "Scienza", "difficolta": "Difficile"},
    {"domanda": "Chi fu il primo imperatore romano ad abbracciare il cristianesimo?", "opzioni": {"a": "Costantino I", "b": "Teodosio", "c": "Giuliano", "d": "Galerio"}, "risposta": "a", "categoria": "Storia", "difficolta": "Difficile"},
    {"domanda": "Quale nazione vinse la Coppa del Mondo di calcio nel 1998?", "opzioni": {"a": "Brasile", "b": "Francia", "c": "Germania", "d": "Italia"}, "risposta": "b", "categoria": "Sport", "difficolta": "Difficile"},
    {"domanda": "Quanti protoni ha l'atomo di Ferro?", "opzioni": {"a": "26", "b": "27", "c": "28", "d": "29"}, "risposta": "a", "categoria": "Scienza", "difficolta": "Difficile"},
]

CATEGORIE = sorted({d["categoria"] for d in DOMANDE_ITALIANE})
DIFFICOLTA = ["Qualsiasi", "Facile", "Media", "Difficile"]
