"""Database di domande quiz in italiano."""

DOMANDE_ITALIANE = [
    # Geografia
    {"domanda": "Qual è la capitale dell'Italia?", "opzioni": {"a": "Milano", "b": "Roma", "c": "Napoli", "d": "Torino"}, "risposta": "b", "categoria": "Geografia", "difficolta": "Facile"},
    {"domanda": "Qual è il fiume più lungo d'Italia?", "opzioni": {"a": "Arno", "b": "Tevere", "c": "Po", "d": "Adige"}, "risposta": "c", "categoria": "Geografia", "difficolta": "Facile"},
    {"domanda": "In quale regione si trova Venezia?", "opzioni": {"a": "Lombardia", "b": "Veneto", "c": "Emilia-Romagna", "d": "Friuli-Venezia Giulia"}, "risposta": "b", "categoria": "Geografia", "difficolta": "Facile"},
    {"domanda": "Qual è la montagna più alta d'Italia?", "opzioni": {"a": "Gran Sasso", "b": "Monte Bianco", "c": "Marmolada", "d": "Etna"}, "risposta": "b", "categoria": "Geografia", "difficolta": "Media"},
    {"domanda": "Qual è la capitale della Francia?", "opzioni": {"a": "Lione", "b": "Marsiglia", "c": "Parigi", "d": "Nizza"}, "risposta": "c", "categoria": "Geografia", "difficolta": "Facile"},
    {"domanda": "Quale oceano bagna la costa occidentale dell'Italia?", "opzioni": {"a": "Atlantico", "b": "Pacifico", "c": "Mediterraneo", "d": "Indiano"}, "risposta": "c", "categoria": "Geografia", "difficolta": "Facile"},
    {"domanda": "Qual è la capitale della Spagna?", "opzioni": {"a": "Barcellona", "b": "Siviglia", "c": "Madrid", "d": "Valencia"}, "risposta": "c", "categoria": "Geografia", "difficolta": "Facile"},
    {"domanda": "In quale continente si trova il Brasile?", "opzioni": {"a": "Africa", "b": "Asia", "c": "America", "d": "Oceania"}, "risposta": "c", "categoria": "Geografia", "difficolta": "Facile"},
    {"domanda": "Qual è il lago più grande d'Italia?", "opzioni": {"a": "Lago di Como", "b": "Lago di Garda", "c": "Lago Maggiore", "d": "Lago di Bolsena"}, "risposta": "b", "categoria": "Geografia", "difficolta": "Media"},
    {"domanda": "Quale stretto separa la Sicilia dalla Calabria?", "opzioni": {"a": "Stretto di Gibilterra", "b": "Stretto di Messina", "c": "Stretto di Otranto", "d": "Canale della Mancia"}, "risposta": "b", "categoria": "Geografia", "difficolta": "Media"},
    # Storia
    {"domanda": "In quale anno è caduto il muro di Berlino?", "opzioni": {"a": "1987", "b": "1989", "c": "1991", "d": "1993"}, "risposta": "b", "categoria": "Storia", "difficolta": "Media"},
    {"domanda": "Chi fu il primo imperatore romano?", "opzioni": {"a": "Giulio Cesare", "b": "Nerone", "c": "Augusto", "d": "Traiano"}, "risposta": "c", "categoria": "Storia", "difficolta": "Media"},
    {"domanda": "In quale anno l'Italia è diventata una Repubblica?", "opzioni": {"a": "1943", "b": "1945", "c": "1946", "d": "1948"}, "risposta": "c", "categoria": "Storia", "difficolta": "Media"},
    {"domanda": "Chi scoprì l'America nel 1492?", "opzioni": {"a": "Marco Polo", "b": "Amerigo Vespucci", "c": "Cristoforo Colombo", "d": "Fernando Magellano"}, "risposta": "c", "categoria": "Storia", "difficolta": "Facile"},
    {"domanda": "In quale secolo è avvenuta la Rivoluzione francese?", "opzioni": {"a": "XV", "b": "XVI", "c": "XVII", "d": "XVIII"}, "risposta": "d", "categoria": "Storia", "difficolta": "Media"},
    {"domanda": "Chi era il leader del fascismo italiano?", "opzioni": {"a": "Garibaldi", "b": "Mussolini", "c": "Cavour", "d": "D'Annunzio"}, "risposta": "b", "categoria": "Storia", "difficolta": "Facile"},
    {"domanda": "In quale anno è iniziata la Prima guerra mondiale?", "opzioni": {"a": "1912", "b": "1914", "c": "1916", "d": "1918"}, "risposta": "b", "categoria": "Storia", "difficolta": "Media"},
    {"domanda": "Chi fu l'ultimo re d'Italia?", "opzioni": {"a": "Vittorio Emanuele II", "b": "Umberto I", "c": "Vittorio Emanuele III", "d": "Umberto II"}, "risposta": "d", "categoria": "Storia", "difficolta": "Difficile"},
    # Scienza
    {"domanda": "Qual è la formula chimica dell'acqua?", "opzioni": {"a": "CO2", "b": "H2O", "c": "O2", "d": "NaCl"}, "risposta": "b", "categoria": "Scienza", "difficolta": "Facile"},
    {"domanda": "Qual è il pianeta più grande del sistema solare?", "opzioni": {"a": "Saturno", "b": "Giove", "c": "Nettuno", "d": "Urano"}, "risposta": "b", "categoria": "Scienza", "difficolta": "Facile"},
    {"domanda": "Quanti pianeti ci sono nel sistema solare?", "opzioni": {"a": "7", "b": "8", "c": "9", "d": "10"}, "risposta": "b", "categoria": "Scienza", "difficolta": "Facile"},
    {"domanda": "Qual è la velocità della luce nel vuoto (circa)?", "opzioni": {"a": "300.000 km/s", "b": "30.000 km/s", "c": "3.000 km/s", "d": "150.000 km/s"}, "risposta": "a", "categoria": "Scienza", "difficolta": "Difficile"},
    {"domanda": "Quale organo pompa il sangue nel corpo umano?", "opzioni": {"a": "Polmoni", "b": "Fegato", "c": "Cuore", "d": "Reni"}, "risposta": "c", "categoria": "Scienza", "difficolta": "Facile"},
    {"domanda": "Qual è il simbolo chimico dell'oro?", "opzioni": {"a": "Ag", "b": "Fe", "c": "Au", "d": "Cu"}, "risposta": "c", "categoria": "Scienza", "difficolta": "Media"},
    {"domanda": "Quanti cromosomi ha una cellula umana normale?", "opzioni": {"a": "23", "b": "46", "c": "48", "d": "64"}, "risposta": "b", "categoria": "Scienza", "difficolta": "Difficile"},
    {"domanda": "Quale gas respirano principalmente le piante di notte?", "opzioni": {"a": "Ossigeno", "b": "Azoto", "c": "Anidride carbonica", "d": "Idrogeno"}, "risposta": "c", "categoria": "Scienza", "difficolta": "Media"},
    {"domanda": "Chi formulò la teoria della relatività?", "opzioni": {"a": "Newton", "b": "Galileo", "c": "Einstein", "d": "Hawking"}, "risposta": "c", "categoria": "Scienza", "difficolta": "Facile"},
    {"domanda": "A quale temperatura l'acqua bolle a livello del mare?", "opzioni": {"a": "90°C", "b": "100°C", "c": "110°C", "d": "80°C"}, "risposta": "b", "categoria": "Scienza", "difficolta": "Facile"},
    # Cultura generale
    {"domanda": "Quanti continenti ci sono sulla Terra?", "opzioni": {"a": "5", "b": "6", "c": "7", "d": "8"}, "risposta": "c", "categoria": "Cultura generale", "difficolta": "Facile"},
    {"domanda": "Quante ore ha un giorno?", "opzioni": {"a": "12", "b": "24", "c": "48", "d": "60"}, "risposta": "b", "categoria": "Cultura generale", "difficolta": "Facile"},
    {"domanda": "Quanti minuti ha un'ora?", "opzioni": {"a": "30", "b": "45", "c": "60", "d": "100"}, "risposta": "c", "categoria": "Cultura generale", "difficolta": "Facile"},
    {"domanda": "Quanti lati ha un triangolo?", "opzioni": {"a": "2", "b": "3", "c": "4", "d": "5"}, "risposta": "b", "categoria": "Cultura generale", "difficolta": "Facile"},
    {"domanda": "Quale linguaggio usiamo in questo progetto?", "opzioni": {"a": "Java", "b": "C++", "c": "Python", "d": "JavaScript"}, "risposta": "c", "categoria": "Cultura generale", "difficolta": "Facile"},
    {"domanda": "Quanti giorni ha un anno bisestile?", "opzioni": {"a": "365", "b": "366", "c": "364", "d": "367"}, "risposta": "b", "categoria": "Cultura generale", "difficolta": "Facile"},
    {"domanda": "Qual è la moneta dell'Unione Europea?", "opzioni": {"a": "Dollaro", "b": "Sterlina", "c": "Euro", "d": "Franco"}, "risposta": "c", "categoria": "Cultura generale", "difficolta": "Facile"},
    {"domanda": "Quante lettere ha l'alfabeto italiano?", "opzioni": {"a": "21", "b": "22", "c": "26", "d": "28"}, "risposta": "a", "categoria": "Cultura generale", "difficolta": "Media"},
    # Arte e letteratura
    {"domanda": "Chi ha dipinto la Gioconda?", "opzioni": {"a": "Michelangelo", "b": "Raffaello", "c": "Leonardo da Vinci", "d": "Donatello"}, "risposta": "c", "categoria": "Arte e letteratura", "difficolta": "Facile"},
    {"domanda": "Chi scrisse 'I Promessi Sposi'?", "opzioni": {"a": "Dante", "b": "Manzoni", "c": "Leopardi", "d": "Pirandello"}, "risposta": "b", "categoria": "Arte e letteratura", "difficolta": "Facile"},
    {"domanda": "Chi scrisse la 'Divina Commedia'?", "opzioni": {"a": "Petrarca", "b": "Boccaccio", "c": "Dante Alighieri", "d": "Ariosto"}, "risposta": "c", "categoria": "Arte e letteratura", "difficolta": "Facile"},
    {"domanda": "Chi dipinse la Cappella Sistina?", "opzioni": {"a": "Raffaello", "b": "Botticelli", "c": "Michelangelo", "d": "Caravaggio"}, "risposta": "c", "categoria": "Arte e letteratura", "difficolta": "Facile"},
    {"domanda": "In quale città si trova il Colosseo?", "opzioni": {"a": "Napoli", "b": "Roma", "c": "Firenze", "d": "Milano"}, "risposta": "b", "categoria": "Arte e letteratura", "difficolta": "Facile"},
    {"domanda": "Chi compose le 'Quattro Stagioni'?", "opzioni": {"a": "Mozart", "b": "Beethoven", "c": "Vivaldi", "d": "Bach"}, "risposta": "c", "categoria": "Arte e letteratura", "difficolta": "Media"},
    {"domanda": "Chi scrisse 'Il nome della rosa'?", "opzioni": {"a": "Calvino", "b": "Eco", "c": "Moravia", "d": "Sciascia"}, "risposta": "b", "categoria": "Arte e letteratura", "difficolta": "Media"},
    # Sport
    {"domanda": "In quale sport si usa un pallone ovale?", "opzioni": {"a": "Calcio", "b": "Basket", "c": "Rugby", "d": "Tennis"}, "risposta": "c", "categoria": "Sport", "difficolta": "Facile"},
    {"domanda": "Quanti giocatori ha una squadra di calcio in campo?", "opzioni": {"a": "9", "b": "10", "c": "11", "d": "12"}, "risposta": "c", "categoria": "Sport", "difficolta": "Facile"},
    {"domanda": "Ogni quanti anni si svolgono le Olimpiadi estive?", "opzioni": {"a": "2", "b": "3", "c": "4", "d": "5"}, "risposta": "c", "categoria": "Sport", "difficolta": "Facile"},
    {"domanda": "In quale sport si usa la racchetta e la pallina gialla?", "opzioni": {"a": "Golf", "b": "Tennis", "c": "Pallavolo", "d": "Baseball"}, "risposta": "b", "categoria": "Sport", "difficolta": "Facile"},
    {"domanda": "Quale paese ha vinto i Mondiali di calcio 2006?", "opzioni": {"a": "Brasile", "b": "Germania", "c": "Italia", "d": "Francia"}, "risposta": "c", "categoria": "Sport", "difficolta": "Facile"},
    {"domanda": "Quanti set si giocano al massimo in una partita di tennis maschile al Grande Slam?", "opzioni": {"a": "3", "b": "4", "c": "5", "d": "7"}, "risposta": "c", "categoria": "Sport", "difficolta": "Media"},
    # Intrattenimento
    {"domanda": "Quale studio ha creato Super Mario?", "opzioni": {"a": "Sega", "b": "Sony", "c": "Nintendo", "d": "Microsoft"}, "risposta": "c", "categoria": "Intrattenimento", "difficolta": "Facile"},
    {"domanda": "Chi interpretò Jack in 'Titanic'?", "opzioni": {"a": "Brad Pitt", "b": "Leonardo DiCaprio", "c": "Tom Cruise", "d": "Johnny Depp"}, "risposta": "b", "categoria": "Intrattenimento", "difficolta": "Facile"},
    {"domanda": "In quale città si svolge il Festival di Sanremo?", "opzioni": {"a": "Roma", "b": "Milano", "c": "Sanremo", "d": "Torino"}, "risposta": "c", "categoria": "Intrattenimento", "difficolta": "Facile"},
    {"domanda": "Quale saga cinematografica include il personaggio Harry Potter?", "opzioni": {"a": "Il Signore degli Anelli", "b": "Star Wars", "c": "Harry Potter", "d": "Marvel"}, "risposta": "c", "categoria": "Intrattenimento", "difficolta": "Facile"},
    {"domanda": "Chi è noto come il 'Re del Pop'?", "opzioni": {"a": "Elvis Presley", "b": "Michael Jackson", "c": "Prince", "d": "Madonna"}, "risposta": "b", "categoria": "Intrattenimento", "difficolta": "Facile"},
    # Italia
    {"domanda": "Qual è il simbolo della Repubblica Italiana?", "opzioni": {"a": "Aquila", "b": "Stella", "c": "Cavallo", "d": "Leone"}, "risposta": "b", "categoria": "Italia", "difficolta": "Media"},
    {"domanda": "Quante regioni ha l'Italia?", "opzioni": {"a": "18", "b": "20", "c": "22", "d": "24"}, "risposta": "b", "categoria": "Italia", "difficolta": "Media"},
    {"domanda": "Qual è la lingua ufficiale dell'Italia?", "opzioni": {"a": "Latino", "b": "Italiano", "c": "Francese", "d": "Tedesco"}, "risposta": "b", "categoria": "Italia", "difficolta": "Facile"},
    {"domanda": "In quale città si trova la Torre di Pisa?", "opzioni": {"a": "Firenze", "b": "Pisa", "c": "Siena", "d": "Lucca"}, "risposta": "b", "categoria": "Italia", "difficolta": "Facile"},
    {"domanda": "Chi compose l'inno di Mameli?", "opzioni": {"a": "Verdi", "b": "Mameli", "c": "Puccini", "d": "Rossini"}, "risposta": "b", "categoria": "Italia", "difficolta": "Media"},
    {"domanda": "Qual è il vulcano attivo più famoso d'Italia?", "opzioni": {"a": "Vesuvio", "b": "Stromboli", "c": "Etna", "d": "Vulcano"}, "risposta": "c", "categoria": "Italia", "difficolta": "Facile"},
    {"domanda": "Quale città italiana è famosa per il Carnevale con le maschere?", "opzioni": {"a": "Roma", "b": "Venezia", "c": "Napoli", "d": "Palermo"}, "risposta": "b", "categoria": "Italia", "difficolta": "Facile"},
    {"domanda": "Chi fu l'eroe dei Mille?", "opzioni": {"a": "Mazzini", "b": "Garibaldi", "c": "Cavour", "d": "Vittorio Emanuele II"}, "risposta": "b", "categoria": "Italia", "difficolta": "Media"},
    # Matematica
    {"domanda": "Quanto fa 7 × 8?", "opzioni": {"a": "54", "b": "56", "c": "58", "d": "64"}, "risposta": "b", "categoria": "Matematica", "difficolta": "Facile"},
    {"domanda": "Quanti gradi ha un angolo retto?", "opzioni": {"a": "45", "b": "90", "c": "180", "d": "360"}, "risposta": "b", "categoria": "Matematica", "difficolta": "Facile"},
    {"domanda": "Qual è il valore di π approssimato a due decimali?", "opzioni": {"a": "3,12", "b": "3,14", "c": "3,16", "d": "3,41"}, "risposta": "b", "categoria": "Matematica", "difficolta": "Media"},
    {"domanda": "Quanto fa 15% di 200?", "opzioni": {"a": "20", "b": "25", "c": "30", "d": "35"}, "risposta": "c", "categoria": "Matematica", "difficolta": "Media"},
    {"domanda": "Quanti lati ha un esagono?", "opzioni": {"a": "5", "b": "6", "c": "7", "d": "8"}, "risposta": "b", "categoria": "Matematica", "difficolta": "Facile"},
    # Animali e natura
    {"domanda": "Qual è l'animale più veloce sulla terra?", "opzioni": {"a": "Leone", "b": "Ghepardo", "c": "Antilope", "d": "Cavallo"}, "risposta": "b", "categoria": "Natura", "difficolta": "Facile"},
    {"domanda": "Quale mammifero marino è il più grande?", "opzioni": {"a": "Squalo balena", "b": "Balena blu", "c": "Orca", "d": "Delfino"}, "risposta": "b", "categoria": "Natura", "difficolta": "Media"},
    {"domanda": "Da cosa si nutrono principalmente le api?", "opzioni": {"a": "Foglie", "b": "Nettare e polline", "c": "Piccoli insetti", "d": "Semi"}, "risposta": "b", "categoria": "Natura", "difficolta": "Facile"},
    {"domanda": "Quale albero produce le olive?", "opzioni": {"a": "Quercia", "b": "Olivo", "c": "Pino", "d": "Betulla"}, "risposta": "b", "categoria": "Natura", "difficolta": "Facile"},
    {"domanda": "Quanti stomaci ha una mucca?", "opzioni": {"a": "1", "b": "2", "c": "3", "d": "4"}, "risposta": "d", "categoria": "Natura", "difficolta": "Difficile"},
    # Domande difficili aggiuntive
    {"domanda": "In quale anno fu firmato il Trattato di Roma, che istituì la CEE?", "opzioni": {"a": "1945", "b": "1957", "c": "1969", "d": "1985"}, "risposta": "b", "categoria": "Storia", "difficolta": "Difficile"},
    {"domanda": "Chi scoprì la penicillina nel 1928?", "opzioni": {"a": "Pasteur", "b": "Fleming", "c": "Koch", "d": "Jenner"}, "risposta": "b", "categoria": "Scienza", "difficolta": "Difficile"},
    {"domanda": "Qual è la capitale dell'Australia?", "opzioni": {"a": "Sydney", "b": "Melbourne", "c": "Canberra", "d": "Perth"}, "risposta": "c", "categoria": "Geografia", "difficolta": "Difficile"},
    {"domanda": "Chi scrisse 'Se questo è un uomo'?", "opzioni": {"a": "Calvino", "b": "Levi", "c": "Pavese", "d": "Montale"}, "risposta": "b", "categoria": "Arte e letteratura", "difficolta": "Difficile"},
    {"domanda": "Quale elemento chimico ha numero atomico 79?", "opzioni": {"a": "Argento", "b": "Ferro", "c": "Oro", "d": "Platino"}, "risposta": "c", "categoria": "Scienza", "difficolta": "Difficile"},
    {"domanda": "In quale anno l'Italia vinse il suo primo Mondiale di calcio?", "opzioni": {"a": "1934", "b": "1938", "c": "1982", "d": "2006"}, "risposta": "a", "categoria": "Sport", "difficolta": "Difficile"},
    {"domanda": "Chi fu il primo presidente della Repubblica Italiana?", "opzioni": {"a": "De Gasperi", "b": "Einaudi", "c": "Gronchi", "d": "Segni"}, "risposta": "b", "categoria": "Italia", "difficolta": "Difficile"},
    {"domanda": "Quale filosofo greco fu maestro di Alessandro Magno?", "opzioni": {"a": "Platone", "b": "Socrate", "c": "Aristotele", "d": "Epicuro"}, "risposta": "c", "categoria": "Storia", "difficolta": "Difficile"},
    {"domanda": "Quanto fa la radice quadrata di 144?", "opzioni": {"a": "10", "b": "11", "c": "12", "d": "14"}, "risposta": "c", "categoria": "Matematica", "difficolta": "Difficile"},
    {"domanda": "Quale organello cellulare produce l'ATP?", "opzioni": {"a": "Nucleo", "b": "Ribosoma", "c": "Mitocondrio", "d": "Lisosoma"}, "risposta": "c", "categoria": "Scienza", "difficolta": "Difficile"},
    # Domande aggiuntive Media
    {"domanda": "Qual è la capitale della Norvegia?", "opzioni": {"a": "Stoccolma", "b": "Oslo", "c": "Copenaghen", "d": "Reykjavik"}, "risposta": "b", "categoria": "Geografia", "difficolta": "Media"},
    {"domanda": "Quanti muscoli ha il corpo umano?", "opzioni": {"a": "206", "b": "316", "c": "400", "d": "500"}, "risposta": "c", "categoria": "Scienza", "difficolta": "Media"},
    {"domanda": "Chi scrisse 'Orgoglio e Pregiudizio'?", "opzioni": {"a": "Jane Austen", "b": "Charlotte Brontë", "c": "George Eliot", "d": "Emily Dickinson"}, "risposta": "a", "categoria": "Arte e letteratura", "difficolta": "Media"},
    {"domanda": "In quale anno fu costruita la Torre Eiffel?", "opzioni": {"a": "1887", "b": "1889", "c": "1891", "d": "1893"}, "risposta": "b", "categoria": "Storia", "difficolta": "Media"},
    {"domanda": "Quanti stati ha gli USA?", "opzioni": {"a": "45", "b": "48", "c": "50", "d": "52"}, "risposta": "c", "categoria": "Geografia", "difficolta": "Media"},
    {"domanda": "Chi dipinse 'La Notte Stellata'?", "opzioni": {"a": "Monet", "b": "Van Gogh", "c": "Cézanne", "d": "Matisse"}, "risposta": "b", "categoria": "Arte e letteratura", "difficolta": "Media"},
    {"domanda": "Qual è l'elemento più leggero della tavola periodica?", "opzioni": {"a": "Elio", "b": "Litio", "c": "Idrogeno", "d": "Neon"}, "risposta": "c", "categoria": "Scienza", "difficolta": "Media"},
    {"domanda": "In quale continente si trova l'Egitto?", "opzioni": {"a": "Asia", "b": "Africa", "c": "Europa", "d": "Oceania"}, "risposta": "b", "categoria": "Geografia", "difficolta": "Media"},
    {"domanda": "Quanti film compongono la trilogia originale di Star Wars?", "opzioni": {"a": "2", "b": "3", "c": "4", "d": "5"}, "risposta": "b", "categoria": "Intrattenimento", "difficolta": "Media"},
    {"domanda": "Chi fu il primo uomo sulla Luna?", "opzioni": {"a": "Buzz Aldrin", "b": "Neil Armstrong", "c": "Michael Collins", "d": "Yuri Gagarin"}, "risposta": "b", "categoria": "Storia", "difficolta": "Media"},
    {"domanda": "Qual è la velocità del suono nell'aria (circa)?", "opzioni": {"a": "300 m/s", "b": "340 m/s", "c": "400 m/s", "d": "500 m/s"}, "risposta": "b", "categoria": "Scienza", "difficolta": "Media"},
    {"domanda": "In quale città si trova il Museo del Prado?", "opzioni": {"a": "Barcellona", "b": "Siviglia", "c": "Madrid", "d": "Valencia"}, "risposta": "c", "categoria": "Arte e letteratura", "difficolta": "Media"},
    {"domanda": "Quanti lati ha un quadrato?", "opzioni": {"a": "3", "b": "4", "c": "5", "d": "6"}, "risposta": "b", "categoria": "Matematica", "difficolta": "Media"},
    {"domanda": "Quale poeta scrisse 'La Struttura della Visione'?", "opzioni": {"a": "Petrarca", "b": "Montale", "c": "Quasimodo", "d": "Giacco"}, "risposta": "b", "categoria": "Arte e letteratura", "difficolta": "Media"},
    {"domanda": "Qual è l'animale terrestre più pesante?", "opzioni": {"a": "Ippopotamo", "b": "Rinoceronte", "c": "Elefante", "d": "Giraffa"}, "risposta": "c", "categoria": "Natura", "difficolta": "Media"},
    {"domanda": "In quale anno scoppiò la Rivoluzione russa?", "opzioni": {"a": "1905", "b": "1917", "c": "1925", "d": "1935"}, "risposta": "b", "categoria": "Storia", "difficolta": "Media"},
    {"domanda": "Qual è il fiume più lungo del mondo?", "opzioni": {"a": "Nilo", "b": "Amazzoni", "c": "Yangtze", "d": "Mississippi"}, "risposta": "a", "categoria": "Geografia", "difficolta": "Media"},
    {"domanda": "Chi scrisse la Bibbia nel Nuovo Testamento?", "opzioni": {"a": "Un autore", "b": "Più autori", "c": "Mosè", "d": "Gesù"}, "risposta": "b", "categoria": "Storia", "difficolta": "Media"},
    # Domande aggiuntive Difficile
    {"domanda": "Chi vinse il Premio Nobel per la Fisica nel 1921?", "opzioni": {"a": "Max Planck", "b": "Albert Einstein", "c": "Niels Bohr", "d": "Erwin Schrödinger"}, "risposta": "b", "categoria": "Scienza", "difficolta": "Difficile"},
    {"domanda": "In quale anno terminò la Guerra dei Trent'anni?", "opzioni": {"a": "1645", "b": "1648", "c": "1652", "d": "1659"}, "risposta": "b", "categoria": "Storia", "difficolta": "Difficile"},
    {"domanda": "Qual è la capitale della Bhutan?", "opzioni": {"a": "Thimphu", "b": "Bumthang", "c": "Paro", "d": "Punakha"}, "risposta": "a", "categoria": "Geografia", "difficolta": "Difficile"},
    {"domanda": "Chi ha dipinto 'Il Giardino delle Delizie'?", "opzioni": {"a": "Bosch", "b": "Dalí", "c": "Magritte", "d": "Ernst"}, "risposta": "a", "categoria": "Arte e letteratura", "difficolta": "Difficile"},
    {"domanda": "Qual è il numero atomico del Carbonio?", "opzioni": {"a": "5", "b": "6", "c": "7", "d": "8"}, "risposta": "b", "categoria": "Scienza", "difficolta": "Difficile"},
    {"domanda": "Chi era il leader politico dell'URSS durante la Seconda guerra mondiale?", "opzioni": {"a": "Lenin", "b": "Trotsky", "c": "Stalin", "d": "Krusciov"}, "risposta": "c", "categoria": "Storia", "difficolta": "Difficile"},
    {"domanda": "In quale paese si trova il Monte Aconcagua?", "opzioni": {"a": "Bolivia", "b": "Cile", "c": "Argentina", "d": "Perù"}, "risposta": "c", "categoria": "Geografia", "difficolta": "Difficile"},
    {"domanda": "Chi scrisse 'Cent'anni di solitudine'?", "opzioni": {"a": "Jorge Luis Borges", "b": "Gabriel García Márquez", "c": "Pablo Neruda", "d": "Carlos Fuentes"}, "risposta": "b", "categoria": "Arte e letteratura", "difficolta": "Difficile"},
    {"domanda": "Quale legge descrive la relazione tra pressione e volume di un gas?", "opzioni": {"a": "Legge di Charles", "b": "Legge di Boyle", "c": "Legge di Gay-Lussac", "d": "Legge di Dalton"}, "risposta": "b", "categoria": "Scienza", "difficolta": "Difficile"},
    {"domanda": "In quale battaglia Napoleone fu definitivamente sconfitto?", "opzioni": {"a": "Waterloo", "b": "Austerlitz", "c": "Borodino", "d": "Lipsia"}, "risposta": "a", "categoria": "Storia", "difficolta": "Difficile"},
    {"domanda": "Qual è la capitale dell'Islanda?", "opzioni": {"a": "Reykjavik", "b": "Akureyri", "c": "Hafnarfjörður", "d": "Kópavogur"}, "risposta": "a", "categoria": "Geografia", "difficolta": "Difficile"},
    {"domanda": "Chi ha composto l'opera 'La Bohème'?", "opzioni": {"a": "Verdi", "b": "Puccini", "c": "Rossini", "d": "Donizetti"}, "risposta": "b", "categoria": "Arte e letteratura", "difficolta": "Difficile"},
    {"domanda": "Quale particella subatomica ha carica negativa?", "opzioni": {"a": "Protone", "b": "Neutrone", "c": "Elettrone", "d": "Positrone"}, "risposta": "c", "categoria": "Scienza", "difficolta": "Difficile"},
    {"domanda": "Chi fu il primo imperatore romano ad abbracciare il cristianesimo?", "opzioni": {"a": "Costantino I", "b": "Teodosio", "c": "Giuliano", "d": "Galerio"}, "risposta": "a", "categoria": "Storia", "difficolta": "Difficile"},
    {"domanda": "Quale nazione vinse la Coppa del Mondo di calcio nel 1998?", "opzioni": {"a": "Brasile", "b": "Francia", "c": "Germania", "d": "Italia"}, "risposta": "b", "categoria": "Sport", "difficolta": "Difficile"},
    {"domanda": "Quanti protoni ha l'atomo di Ferro?", "opzioni": {"a": "26", "b": "27", "c": "28", "d": "29"}, "risposta": "a", "categoria": "Scienza", "difficolta": "Difficile"},
    # Arte e letteratura - Facile
    {"domanda": "Chi scrisse 'Pinocchio'?", "opzioni": {"a": "Collodi", "b": "Manzoni", "c": "D'Annunzio", "d": "Verga"}, "risposta": "a", "categoria": "Arte e letteratura", "difficolta": "Facile"},
    {"domanda": "In quale città si trova il Duomo con la cupola di Brunelleschi?", "opzioni": {"a": "Roma", "b": "Firenze", "c": "Milano", "d": "Siena"}, "risposta": "b", "categoria": "Arte e letteratura", "difficolta": "Facile"},
    {"domanda": "Chi dipinse 'L'Ultima Cena'?", "opzioni": {"a": "Raffaello", "b": "Tiziano", "c": "Leonardo da Vinci", "d": "Caravaggio"}, "risposta": "c", "categoria": "Arte e letteratura", "difficolta": "Facile"},
    {"domanda": "Chi compose 'La Traviata'?", "opzioni": {"a": "Verdi", "b": "Puccini", "c": "Rossini", "d": "Donizetti"}, "risposta": "a", "categoria": "Arte e letteratura", "difficolta": "Facile"},
    {"domanda": "Quale scultore realizzò il David di Firenze?", "opzioni": {"a": "Donatello", "b": "Bernini", "c": "Michelangelo", "d": "Canova"}, "risposta": "c", "categoria": "Arte e letteratura", "difficolta": "Facile"},
    # Arte e letteratura - Media
    {"domanda": "Chi scrisse 'Il Gattopardo'?", "opzioni": {"a": "Lampedusa", "b": "Moravia", "c": "Sciascia", "d": "Calvino"}, "risposta": "a", "categoria": "Arte e letteratura", "difficolta": "Media"},
    {"domanda": "Quale movimento artistico è associato a Salvador Dalí?", "opzioni": {"a": "Impressionismo", "b": "Cubismo", "c": "Surrealismo", "d": "Futurismo"}, "risposta": "c", "categoria": "Arte e letteratura", "difficolta": "Media"},
    # Arte e letteratura - Difficile
    {"domanda": "Chi scrisse 'Ulisse'?", "opzioni": {"a": "Beckett", "b": "Joyce", "c": "Woolf", "d": "Proust"}, "risposta": "b", "categoria": "Arte e letteratura", "difficolta": "Difficile"},
    {"domanda": "Quale architetto progettò la Villa Savoye?", "opzioni": {"a": "Wright", "b": "Le Corbusier", "c": "Mies van der Rohe", "d": "Gaudí"}, "risposta": "b", "categoria": "Arte e letteratura", "difficolta": "Difficile"},
    {"domanda": "Chi compose l'opera 'L'Orfeo'?", "opzioni": {"a": "Monteverdi", "b": "Handel", "c": "Vivaldi", "d": "Corelli"}, "risposta": "a", "categoria": "Arte e letteratura", "difficolta": "Difficile"},
    # Cultura generale - Facile
    {"domanda": "Quanti mesi ha un anno?", "opzioni": {"a": "10", "b": "11", "c": "12", "d": "13"}, "risposta": "c", "categoria": "Cultura generale", "difficolta": "Facile"},
    {"domanda": "Quale colore si ottiene mescolando rosso e blu?", "opzioni": {"a": "Verde", "b": "Arancione", "c": "Viola", "d": "Marrone"}, "risposta": "c", "categoria": "Cultura generale", "difficolta": "Facile"},
    {"domanda": "Quanti giorni ha una settimana?", "opzioni": {"a": "5", "b": "6", "c": "7", "d": "8"}, "risposta": "c", "categoria": "Cultura generale", "difficolta": "Facile"},
    # Cultura generale - Media
    {"domanda": "Quale organizzazione ha sede a Ginevra e si occupa di salute globale?", "opzioni": {"a": "UNESCO", "b": "OMS", "c": "FAO", "d": "UNICEF"}, "risposta": "b", "categoria": "Cultura generale", "difficolta": "Media"},
    {"domanda": "Quale strumento misura la pressione atmosferica?", "opzioni": {"a": "Termometro", "b": "Barometro", "c": "Anemometro", "d": "Igrometro"}, "risposta": "b", "categoria": "Cultura generale", "difficolta": "Media"},
    {"domanda": "In quale paese è nato il tango?", "opzioni": {"a": "Brasile", "b": "Messico", "c": "Argentina", "d": "Spagna"}, "risposta": "c", "categoria": "Cultura generale", "difficolta": "Media"},
    {"domanda": "Quale festa cade il 25 dicembre?", "opzioni": {"a": "Capodanno", "b": "Epifania", "c": "Natale", "d": "Pasqua"}, "risposta": "c", "categoria": "Cultura generale", "difficolta": "Media"},
    {"domanda": "Quanti secondi ha un minuto?", "opzioni": {"a": "30", "b": "45", "c": "60", "d": "100"}, "risposta": "c", "categoria": "Cultura generale", "difficolta": "Media"},
    {"domanda": "Quale lingua è parlata in Brasile?", "opzioni": {"a": "Spagnolo", "b": "Portoghese", "c": "Francese", "d": "Italiano"}, "risposta": "b", "categoria": "Cultura generale", "difficolta": "Media"},
    {"domanda": "Quale simbolo indica il copyright?", "opzioni": {"a": "™", "b": "©", "c": "®", "d": "§"}, "risposta": "b", "categoria": "Cultura generale", "difficolta": "Media"},
    # Cultura generale - Difficile
    {"domanda": "Quale filosofo scrisse 'Critica della ragion pura'?", "opzioni": {"a": "Hegel", "b": "Kant", "c": "Descartes", "d": "Hume"}, "risposta": "b", "categoria": "Cultura generale", "difficolta": "Difficile"},
    {"domanda": "In quale anno è stato creato il World Wide Web?", "opzioni": {"a": "1985", "b": "1989", "c": "1993", "d": "1997"}, "risposta": "b", "categoria": "Cultura generale", "difficolta": "Difficile"},
    {"domanda": "Quale paese ha inventato la carta?", "opzioni": {"a": "Giappone", "b": "Egitto", "c": "Cina", "d": "India"}, "risposta": "c", "categoria": "Cultura generale", "difficolta": "Difficile"},
    {"domanda": "Quale trattato istituì l'ONU nel 1945?", "opzioni": {"a": "Trattato di Versailles", "b": "Carta di San Francisco", "c": "Trattato di Parigi", "d": "Patto di Varsavia"}, "risposta": "b", "categoria": "Cultura generale", "difficolta": "Difficile"},
    {"domanda": "Quale scienziato propose il modello elicoidale del DNA?", "opzioni": {"a": "Franklin", "b": "Watson e Crick", "c": "Mendel", "d": "Pasteur"}, "risposta": "b", "categoria": "Cultura generale", "difficolta": "Difficile"},
    {"domanda": "Quale città ospita la sede principale dell'ONU?", "opzioni": {"a": "Ginevra", "b": "New York", "c": "Bruxelles", "d": "L'Aia"}, "risposta": "b", "categoria": "Cultura generale", "difficolta": "Difficile"},
    # Geografia - Facile
    {"domanda": "Qual è la capitale della Germania?", "opzioni": {"a": "Monaco", "b": "Francoforte", "c": "Berlino", "d": "Amburgo"}, "risposta": "c", "categoria": "Geografia", "difficolta": "Facile"},
    {"domanda": "Quale mare bagna la costa orientale dell'Italia?", "opzioni": {"a": "Tirreno", "b": "Adriatico", "c": "Ligure", "d": "Jonio"}, "risposta": "b", "categoria": "Geografia", "difficolta": "Facile"},
    {"domanda": "In quale continente si trova il Canada?", "opzioni": {"a": "Europa", "b": "Asia", "c": "America", "d": "Oceania"}, "risposta": "c", "categoria": "Geografia", "difficolta": "Facile"},
    # Geografia - Difficile
    {"domanda": "Qual è la capitale del Kazakistan?", "opzioni": {"a": "Almaty", "b": "Astana", "c": "Bishkek", "d": "Tashkent"}, "risposta": "b", "categoria": "Geografia", "difficolta": "Difficile"},
    {"domanda": "Quale deserto è il più grande del mondo?", "opzioni": {"a": "Gobi", "b": "Kalahari", "c": "Sahara", "d": "Antartico"}, "risposta": "d", "categoria": "Geografia", "difficolta": "Difficile"},
    {"domanda": "In quale paese si trova la città di Marrakech?", "opzioni": {"a": "Algeria", "b": "Tunisia", "c": "Marocco", "d": "Libia"}, "risposta": "c", "categoria": "Geografia", "difficolta": "Difficile"},
    # Intrattenimento - Facile
    {"domanda": "Quale supereroe è conosciuto come 'Uomo Ragno'?", "opzioni": {"a": "Batman", "b": "Superman", "c": "Spider-Man", "d": "Iron Man"}, "risposta": "c", "categoria": "Intrattenimento", "difficolta": "Facile"},
    {"domanda": "Chi interpretò Iron Man nel Marvel Cinematic Universe?", "opzioni": {"a": "Chris Evans", "b": "Robert Downey Jr.", "c": "Chris Hemsworth", "d": "Mark Ruffalo"}, "risposta": "b", "categoria": "Intrattenimento", "difficolta": "Facile"},
    {"domanda": "Quale console ha prodotto il gioco 'The Legend of Zelda'?", "opzioni": {"a": "PlayStation", "b": "Xbox", "c": "Nintendo", "d": "Sega"}, "risposta": "c", "categoria": "Intrattenimento", "difficolta": "Facile"},
    {"domanda": "In quale film compare il personaggio Elsa?", "opzioni": {"a": "Moana", "b": "Frozen", "c": "Encanto", "d": "Brave"}, "risposta": "b", "categoria": "Intrattenimento", "difficolta": "Facile"},
    {"domanda": "Quale band britannica cantò 'Bohemian Rhapsody'?", "opzioni": {"a": "The Beatles", "b": "Queen", "c": "Led Zeppelin", "d": "The Rolling Stones"}, "risposta": "b", "categoria": "Intrattenimento", "difficolta": "Facile"},
    # Intrattenimento - Media
    {"domanda": "Chi ha diretto 'Il Padrino'?", "opzioni": {"a": "Scorsese", "b": "Coppola", "c": "Spielberg", "d": "Tarantino"}, "risposta": "b", "categoria": "Intrattenimento", "difficolta": "Media"},
    {"domanda": "Quale serie TV è ambientata a Westeros?", "opzioni": {"a": "Breaking Bad", "b": "Game of Thrones", "c": "The Crown", "d": "Stranger Things"}, "risposta": "b", "categoria": "Intrattenimento", "difficolta": "Media"},
    {"domanda": "Chi cantò 'Shape of You'?", "opzioni": {"a": "Ed Sheeran", "b": "Bruno Mars", "c": "Justin Bieber", "d": "The Weeknd"}, "risposta": "a", "categoria": "Intrattenimento", "difficolta": "Media"},
    {"domanda": "Quale attore interpretò Joker nel film del 2019?", "opzioni": {"a": "Heath Ledger", "b": "Joaquin Phoenix", "c": "Jared Leto", "d": "Jack Nicholson"}, "risposta": "b", "categoria": "Intrattenimento", "difficolta": "Media"},
    {"domanda": "In quale paese è nato il K-pop?", "opzioni": {"a": "Giappone", "b": "Cina", "c": "Corea del Sud", "d": "Thailandia"}, "risposta": "c", "categoria": "Intrattenimento", "difficolta": "Media"},
    {"domanda": "Quale regista ha creato 'E.T. l'extra-terrestre'?", "opzioni": {"a": "Lucas", "b": "Spielberg", "c": "Cameron", "d": "Nolan"}, "risposta": "b", "categoria": "Intrattenimento", "difficolta": "Media"},
    {"domanda": "Quale cantante italiano è soprannominato 'Il Re del Pop italiano'?", "opzioni": {"a": "Vasco Rossi", "b": "Jovanotti", "c": "Baglioni", "d": "Battiato"}, "risposta": "a", "categoria": "Intrattenimento", "difficolta": "Media"},
    # Intrattenimento - Difficile
    {"domanda": "Quale film vinse l'Oscar al miglior film nel 2020?", "opzioni": {"a": "1917", "b": "Parasite", "c": "Joker", "d": "Once Upon a Time in Hollywood"}, "risposta": "b", "categoria": "Intrattenimento", "difficolta": "Difficile"},
    {"domanda": "Chi compose la colonna sonora de 'Il Signore degli Anelli'?", "opzioni": {"a": "John Williams", "b": "Hans Zimmer", "c": "Howard Shore", "d": "Ennio Morricone"}, "risposta": "c", "categoria": "Intrattenimento", "difficolta": "Difficile"},
    {"domanda": "In quale anno uscì il primo film de 'Star Wars'?", "opzioni": {"a": "1975", "b": "1977", "c": "1979", "d": "1980"}, "risposta": "b", "categoria": "Intrattenimento", "difficolta": "Difficile"},
    {"domanda": "Quale studio ha prodotto 'Toy Story'?", "opzioni": {"a": "DreamWorks", "b": "Pixar", "c": "Blue Sky", "d": "Illumination"}, "risposta": "b", "categoria": "Intrattenimento", "difficolta": "Difficile"},
    {"domanda": "Chi scrisse la saga 'Il Signore degli Anelli'?", "opzioni": {"a": "C.S. Lewis", "b": "J.R.R. Tolkien", "c": "George R.R. Martin", "d": "Terry Pratchett"}, "risposta": "b", "categoria": "Intrattenimento", "difficolta": "Difficile"},
    {"domanda": "Quale album dei Pink Floyd contiene 'Another Brick in the Wall'?", "opzioni": {"a": "Dark Side of the Moon", "b": "The Wall", "c": "Wish You Were Here", "d": "Animals"}, "risposta": "b", "categoria": "Intrattenimento", "difficolta": "Difficile"},
    # Italia - Facile
    {"domanda": "Qual è la capitale della Lombardia?", "opzioni": {"a": "Bergamo", "b": "Milano", "c": "Brescia", "d": "Como"}, "risposta": "b", "categoria": "Italia", "difficolta": "Facile"},
    {"domanda": "Quale piatto italiano è fatto con pasta, uova, guanciale e pecorino?", "opzioni": {"a": "Carbonara", "b": "Amatriciana", "c": "Cacio e pepe", "d": "Arrabbiata"}, "risposta": "a", "categoria": "Italia", "difficolta": "Facile"},
    {"domanda": "In quale regione si trova Napoli?", "opzioni": {"a": "Puglia", "b": "Campania", "c": "Calabria", "d": "Basilicata"}, "risposta": "b", "categoria": "Italia", "difficolta": "Facile"},
    {"domanda": "Quale città italiana è famosa per il Duomo gotico?", "opzioni": {"a": "Torino", "b": "Milano", "c": "Genova", "d": "Bologna"}, "risposta": "b", "categoria": "Italia", "difficolta": "Facile"},
    {"domanda": "Quale isola italiana è la più grande?", "opzioni": {"a": "Sardegna", "b": "Sicilia", "c": "Elba", "d": "Ischia"}, "risposta": "b", "categoria": "Italia", "difficolta": "Facile"},
    {"domanda": "Quale città è sede della Banca d'Italia?", "opzioni": {"a": "Milano", "b": "Roma", "c": "Torino", "d": "Firenze"}, "risposta": "b", "categoria": "Italia", "difficolta": "Facile"},
    # Italia - Media
    {"domanda": "In quale anno è entrata l'Italia nell'euro?", "opzioni": {"a": "1999", "b": "2000", "c": "2002", "d": "2005"}, "risposta": "c", "categoria": "Italia", "difficolta": "Media"},
    {"domanda": "Quale regione italiana confina con Austria e Svizzera?", "opzioni": {"a": "Veneto", "b": "Trentino-Alto Adige", "c": "Friuli-Venezia Giulia", "d": "Lombardia"}, "risposta": "b", "categoria": "Italia", "difficolta": "Media"},
    {"domanda": "Quale città italiana è famosa per la Mole Antonelliana?", "opzioni": {"a": "Genova", "b": "Torino", "c": "Trieste", "d": "Padova"}, "risposta": "b", "categoria": "Italia", "difficolta": "Media"},
    {"domanda": "Quale presidente della Repubblica fu eletto nel 2015?", "opzioni": {"a": "Napolitano", "b": "Mattarella", "c": "Ciampi", "d": "Scalfaro"}, "risposta": "b", "categoria": "Italia", "difficolta": "Media"},
    # Italia - Difficile
    {"domanda": "In quale anno fu proclamato il Regno d'Italia?", "opzioni": {"a": "1848", "b": "1861", "c": "1870", "d": "1871"}, "risposta": "b", "categoria": "Italia", "difficolta": "Difficile"},
    {"domanda": "Quale trattato pose fine alla Prima guerra mondiale per l'Italia?", "opzioni": {"a": "Trattato di Versailles", "b": "Trattato di Rapallo", "c": "Trattato di San Germano", "d": "Trattato di Trianon"}, "risposta": "c", "categoria": "Italia", "difficolta": "Difficile"},
    {"domanda": "Chi fu il fondatore del Partito Comunista Italiano?", "opzioni": {"a": "Togliatti", "b": "Gramsci", "c": "Berlinguer", "d": "Pertini"}, "risposta": "b", "categoria": "Italia", "difficolta": "Difficile"},
    {"domanda": "Quale città fu capitale del Regno delle Due Sicilie?", "opzioni": {"a": "Palermo", "b": "Napoli", "c": "Bari", "d": "Catania"}, "risposta": "b", "categoria": "Italia", "difficolta": "Difficile"},
    {"domanda": "In quale anno fu approvata la Costituzione italiana?", "opzioni": {"a": "1946", "b": "1947", "c": "1948", "d": "1950"}, "risposta": "c", "categoria": "Italia", "difficolta": "Difficile"},
    {"domanda": "Quale scienziato italiano inventò la radio?", "opzioni": {"a": "Volta", "b": "Galilei", "c": "Marconi", "d": "Fermi"}, "risposta": "c", "categoria": "Italia", "difficolta": "Difficile"},
    # Matematica - Facile
    {"domanda": "Quanto fa 9 + 6?", "opzioni": {"a": "14", "b": "15", "c": "16", "d": "17"}, "risposta": "b", "categoria": "Matematica", "difficolta": "Facile"},
    {"domanda": "Quanti lati ha un pentagono?", "opzioni": {"a": "4", "b": "5", "c": "6", "d": "7"}, "risposta": "b", "categoria": "Matematica", "difficolta": "Facile"},
    {"domanda": "Quanto fa 12 ÷ 3?", "opzioni": {"a": "3", "b": "4", "c": "5", "d": "6"}, "risposta": "b", "categoria": "Matematica", "difficolta": "Facile"},
    {"domanda": "Quale numero è pari?", "opzioni": {"a": "13", "b": "17", "c": "22", "d": "31"}, "risposta": "c", "categoria": "Matematica", "difficolta": "Facile"},
    {"domanda": "Quanti gradi ha un angolo piatto?", "opzioni": {"a": "90", "b": "120", "c": "180", "d": "360"}, "risposta": "c", "categoria": "Matematica", "difficolta": "Facile"},
    {"domanda": "Quanto fa 5 × 5?", "opzioni": {"a": "20", "b": "25", "c": "30", "d": "35"}, "risposta": "b", "categoria": "Matematica", "difficolta": "Facile"},
    {"domanda": "Quale frazione equivale a 0,5?", "opzioni": {"a": "1/3", "b": "1/2", "c": "2/3", "d": "3/4"}, "risposta": "b", "categoria": "Matematica", "difficolta": "Facile"},
    # Matematica - Media
    {"domanda": "Quanto fa 25% di 80?", "opzioni": {"a": "15", "b": "20", "c": "25", "d": "30"}, "risposta": "b", "categoria": "Matematica", "difficolta": "Media"},
    {"domanda": "Quale è il perimetro di un quadrato con lato 5?", "opzioni": {"a": "10", "b": "15", "c": "20", "d": "25"}, "risposta": "c", "categoria": "Matematica", "difficolta": "Media"},
    {"domanda": "Quanto fa 3 elevato alla 3?", "opzioni": {"a": "6", "b": "9", "c": "27", "d": "81"}, "risposta": "c", "categoria": "Matematica", "difficolta": "Media"},
    {"domanda": "Quale numero è primo?", "opzioni": {"a": "9", "b": "15", "c": "17", "d": "21"}, "risposta": "c", "categoria": "Matematica", "difficolta": "Media"},
    {"domanda": "Quanto fa la media tra 10 e 20?", "opzioni": {"a": "12", "b": "15", "c": "18", "d": "25"}, "risposta": "b", "categoria": "Matematica", "difficolta": "Media"},
    # Matematica - Difficile
    {"domanda": "Quanto fa logaritmo in base 10 di 1000?", "opzioni": {"a": "2", "b": "3", "c": "4", "d": "10"}, "risposta": "b", "categoria": "Matematica", "difficolta": "Difficile"},
    {"domanda": "Quanti gradi ha la somma degli angoli interni di un triangolo?", "opzioni": {"a": "90", "b": "180", "c": "270", "d": "360"}, "risposta": "b", "categoria": "Matematica", "difficolta": "Difficile"},
    {"domanda": "Quale è l'area di un cerchio con raggio 2? (π ≈ 3,14)", "opzioni": {"a": "6,28", "b": "12,56", "c": "18,84", "d": "25,12"}, "risposta": "b", "categoria": "Matematica", "difficolta": "Difficile"},
    {"domanda": "Quanto fa 2 elevato alla 10?", "opzioni": {"a": "512", "b": "1024", "c": "2048", "d": "4096"}, "risposta": "b", "categoria": "Matematica", "difficolta": "Difficile"},
    {"domanda": "Quale sequenza è una progressione aritmetica?", "opzioni": {"a": "2, 4, 8, 16", "b": "3, 6, 9, 12", "c": "1, 4, 9, 16", "d": "5, 10, 20, 40"}, "risposta": "b", "categoria": "Matematica", "difficolta": "Difficile"},
    {"domanda": "Quanto fa la radice cubica di 27?", "opzioni": {"a": "2", "b": "3", "c": "4", "d": "9"}, "risposta": "b", "categoria": "Matematica", "difficolta": "Difficile"},
    # Natura - Facile
    {"domanda": "Quale animale è famoso per cambiare colore?", "opzioni": {"a": "Camaleonte", "b": "Geco", "c": "Iguana", "d": "Lucertola"}, "risposta": "a", "categoria": "Natura", "difficolta": "Facile"},
    {"domanda": "Da quale parte del corpo respirano i pesci?", "opzioni": {"a": "Pelle", "b": "Branchie", "c": "Pinne", "d": "Coda"}, "risposta": "b", "categoria": "Natura", "difficolta": "Facile"},
    {"domanda": "Quale animale è il simbolo della pace?", "opzioni": {"a": "Aquila", "b": "Colomba", "c": "Cigno", "d": "Gufo"}, "risposta": "b", "categoria": "Natura", "difficolta": "Facile"},
    {"domanda": "Quale pianta produce il caffè?", "opzioni": {"a": "Cacao", "b": "Caffè", "c": "Tè", "d": "Vaniglia"}, "risposta": "b", "categoria": "Natura", "difficolta": "Facile"},
    {"domanda": "Quale animale ha una proboscide?", "opzioni": {"a": "Rinoceronte", "b": "Elefante", "c": "Ippopotamo", "d": "Giraffa"}, "risposta": "b", "categoria": "Natura", "difficolta": "Facile"},
    {"domanda": "Quale uccello non vola ed è il più grande del mondo?", "opzioni": {"a": "Emù", "b": "Struzzo", "c": "Pinguino", "d": "Casuario"}, "risposta": "b", "categoria": "Natura", "difficolta": "Facile"},
    {"domanda": "Quale gas è essenziale per la respirazione umana?", "opzioni": {"a": "Azoto", "b": "Ossigeno", "c": "Anidride carbonica", "d": "Idrogeno"}, "risposta": "b", "categoria": "Natura", "difficolta": "Facile"},
    # Natura - Media
    {"domanda": "Quale processo usano le piante per produrre energia dalla luce?", "opzioni": {"a": "Respirazione", "b": "Fotosintesi", "c": "Fermentazione", "d": "Digestione"}, "risposta": "b", "categoria": "Natura", "difficolta": "Media"},
    {"domanda": "Quale mammifero volante è attivo di notte?", "opzioni": {"a": "Gufo", "b": "Pipistrello", "c": "Rondine", "d": "Colibrì"}, "risposta": "b", "categoria": "Natura", "difficolta": "Media"},
    {"domanda": "Quale animale vive sia in acqua che sulla terra?", "opzioni": {"a": "Rana", "b": "Pesce", "c": "Serpente", "d": "Tartaruga di mare"}, "risposta": "a", "categoria": "Natura", "difficolta": "Media"},
    {"domanda": "Quale albero perde le foglie in autunno?", "opzioni": {"a": "Pino", "b": "Abete", "c": "Quercia", "d": "Cipresso"}, "risposta": "c", "categoria": "Natura", "difficolta": "Media"},
    {"domanda": "Quale organo filtra il sangue nel corpo umano?", "opzioni": {"a": "Cuore", "b": "Polmoni", "c": "Reni", "d": "Stomaco"}, "risposta": "c", "categoria": "Natura", "difficolta": "Media"},
    {"domanda": "Quale insetto produce la seta?", "opzioni": {"a": "Ape", "b": "Baco da seta", "c": "Formica", "d": "Libellula"}, "risposta": "b", "categoria": "Natura", "difficolta": "Media"},
    # Natura - Difficile
    {"domanda": "Quale strato dell'atmosfera contiene lo strato di ozono?", "opzioni": {"a": "Troposfera", "b": "Stratosfera", "c": "Mesosfera", "d": "Termosfera"}, "risposta": "b", "categoria": "Natura", "difficolta": "Difficile"},
    {"domanda": "Quale animale ha il cuore diviso in quattro camere?", "opzioni": {"a": "Pesce", "b": "Rana", "c": "Mammifero", "d": "Insetto"}, "risposta": "c", "categoria": "Natura", "difficolta": "Difficile"},
    {"domanda": "Quale bioma ha la maggiore biodiversità?", "opzioni": {"a": "Tundra", "b": "Deserto", "c": "Foresta pluviale", "d": "Taiga"}, "risposta": "c", "categoria": "Natura", "difficolta": "Difficile"},
    {"domanda": "Quale processo trasforma la roccia in suolo nel tempo?", "opzioni": {"a": "Erosione", "b": "Metamorfismo", "c": "Erosione e alterazione", "d": "Vulcanismo"}, "risposta": "c", "categoria": "Natura", "difficolta": "Difficile"},
    {"domanda": "Quale animale è endemico dell'Australia?", "opzioni": {"a": "Panda", "b": "Koala", "c": "Orso polare", "d": "Tigre"}, "risposta": "b", "categoria": "Natura", "difficolta": "Difficile"},
    {"domanda": "Quale tipo di legame tiene insieme le molecole d'acqua?", "opzioni": {"a": "Legame ionico", "b": "Legame covalente", "c": "Legame idrogeno", "d": "Legame metallico"}, "risposta": "c", "categoria": "Natura", "difficolta": "Difficile"},
    # Scienza - Facile
    {"domanda": "Qual è il pianeta più vicino al Sole?", "opzioni": {"a": "Venere", "b": "Mercurio", "c": "Marte", "d": "Terra"}, "risposta": "b", "categoria": "Scienza", "difficolta": "Facile"},
    {"domanda": "Quale organo umano produce la bile?", "opzioni": {"a": "Stomaco", "b": "Fegato", "c": "Pancreas", "d": "Milza"}, "risposta": "b", "categoria": "Scienza", "difficolta": "Facile"},
    {"domanda": "Quale forza ci tiene attaccati al suolo?", "opzioni": {"a": "Magnetismo", "b": "Gravità", "c": "Elettricità", "d": "Attrito"}, "risposta": "b", "categoria": "Scienza", "difficolta": "Facile"},
    {"domanda": "Quale metallo è liquido a temperatura ambiente?", "opzioni": {"a": "Alluminio", "b": "Mercurio", "c": "Ferro", "d": "Rame"}, "risposta": "b", "categoria": "Scienza", "difficolta": "Facile"},
    # Scienza - Media
    {"domanda": "Quale unità misura l'intensità della corrente elettrica?", "opzioni": {"a": "Volt", "b": "Ampere", "c": "Ohm", "d": "Watt"}, "risposta": "b", "categoria": "Scienza", "difficolta": "Media"},
    {"domanda": "Quale pianeta è soprannominato il 'Pianeta Rosso'?", "opzioni": {"a": "Giove", "b": "Saturno", "c": "Marte", "d": "Venere"}, "risposta": "c", "categoria": "Scienza", "difficolta": "Media"},
    {"domanda": "Quale scienziato formulò le tre leggi del moto?", "opzioni": {"a": "Galileo", "b": "Newton", "c": "Keplero", "d": "Copernico"}, "risposta": "b", "categoria": "Scienza", "difficolta": "Media"},
    # Sport - Facile
    {"domanda": "In quale sport si segna un canestro?", "opzioni": {"a": "Calcio", "b": "Basket", "c": "Rugby", "d": "Hockey"}, "risposta": "b", "categoria": "Sport", "difficolta": "Facile"},
    {"domanda": "Quanti giocatori ha una squadra di pallavolo in campo?", "opzioni": {"a": "5", "b": "6", "c": "7", "d": "11"}, "risposta": "b", "categoria": "Sport", "difficolta": "Facile"},
    {"domanda": "In quale sport si usa il puck?", "opzioni": {"a": "Hockey su ghiaccio", "b": "Polo", "c": "Cricket", "d": "Golf"}, "risposta": "a", "categoria": "Sport", "difficolta": "Facile"},
    {"domanda": "Quale paese ha inventato il judo?", "opzioni": {"a": "Cina", "b": "Corea", "c": "Giappone", "d": "Thailandia"}, "risposta": "c", "categoria": "Sport", "difficolta": "Facile"},
    {"domanda": "Quanti giri ha una pista olimpica di atletica?", "opzioni": {"a": "1", "b": "2", "c": "2,5", "d": "4"}, "risposta": "c", "categoria": "Sport", "difficolta": "Facile"},
    # Sport - Media
    {"domanda": "Quale ciclista italiano vinse il Tour de France nel 1998?", "opzioni": {"a": "Pantani", "b": "Nibali", "c": "Coppi", "d": "Bartali"}, "risposta": "a", "categoria": "Sport", "difficolta": "Media"},
    {"domanda": "In quale sport si usa il termine 'ace'?", "opzioni": {"a": "Golf", "b": "Tennis", "c": "Calcio", "d": "Nuoto"}, "risposta": "b", "categoria": "Sport", "difficolta": "Media"},
    {"domanda": "Quanti punti vale un touchdown nel football americano?", "opzioni": {"a": "3", "b": "6", "c": "7", "d": "8"}, "risposta": "b", "categoria": "Sport", "difficolta": "Media"},
    {"domanda": "Quale squadra italiana ha vinto più volte la Champions League?", "opzioni": {"a": "Inter", "b": "Milan", "c": "Juventus", "d": "Roma"}, "risposta": "b", "categoria": "Sport", "difficolta": "Media"},
    {"domanda": "In quale città si svolge il torneo di Wimbledon?", "opzioni": {"a": "Parigi", "b": "Londra", "c": "New York", "d": "Melbourne"}, "risposta": "b", "categoria": "Sport", "difficolta": "Media"},
    {"domanda": "Quale nuotatore ha vinto 8 medaglie d'oro alle Olimpiadi di Pechino 2008?", "opzioni": {"a": "Phelps", "b": "Thorpe", "c": "Spitz", "d": "Popov"}, "risposta": "a", "categoria": "Sport", "difficolta": "Media"},
    {"domanda": "Quanti giocatori compongono una squadra di water polo in vasca?", "opzioni": {"a": "5", "b": "6", "c": "7", "d": "11"}, "risposta": "c", "categoria": "Sport", "difficolta": "Media"},
    # Sport - Difficile
    {"domanda": "In quale anno si tenne la prima Coppa del Mondo FIFA?", "opzioni": {"a": "1926", "b": "1930", "c": "1934", "d": "1938"}, "risposta": "b", "categoria": "Sport", "difficolta": "Difficile"},
    {"domanda": "Quale atleta detiene il record del mondo nei 100 metri (9,58)?", "opzioni": {"a": "Carl Lewis", "b": "Usain Bolt", "c": "Tyson Gay", "d": "Justin Gatlin"}, "risposta": "b", "categoria": "Sport", "difficolta": "Difficile"},
    {"domanda": "Quale paese ha vinto più Coppe del Mondo di calcio?", "opzioni": {"a": "Germania", "b": "Italia", "c": "Brasile", "d": "Argentina"}, "risposta": "c", "categoria": "Sport", "difficolta": "Difficile"},
    {"domanda": "In quale anno Maradona segnò la 'Mano de Dios'?", "opzioni": {"a": "1982", "b": "1986", "c": "1990", "d": "1994"}, "risposta": "b", "categoria": "Sport", "difficolta": "Difficile"},
    # Storia - Facile
    {"domanda": "In quale secolo visse Leonardo da Vinci?", "opzioni": {"a": "XIV", "b": "XV", "c": "XVI", "d": "XVII"}, "risposta": "b", "categoria": "Storia", "difficolta": "Facile"},
    {"domanda": "Chi fu il faraone più famoso dell'antico Egitto?", "opzioni": {"a": "Cleopatra", "b": "Tutankhamon", "c": "Ramses II", "d": "Akhenaton"}, "risposta": "b", "categoria": "Storia", "difficolta": "Facile"},
    {"domanda": "In quale anno finì la Seconda guerra mondiale in Europa?", "opzioni": {"a": "1943", "b": "1944", "c": "1945", "d": "1946"}, "risposta": "c", "categoria": "Storia", "difficolta": "Facile"},
    {"domanda": "Chi fu il primo uomo nello spazio?", "opzioni": {"a": "Neil Armstrong", "b": "Yuri Gagarin", "c": "Alan Shepard", "d": "John Glenn"}, "risposta": "b", "categoria": "Storia", "difficolta": "Facile"},
    {"domanda": "Quale impero costruì il Colosseo?", "opzioni": {"a": "Greco", "b": "Romano", "c": "Bizantino", "d": "Ottomano"}, "risposta": "b", "categoria": "Storia", "difficolta": "Facile"},
    {"domanda": "In quale paese nacque Adolf Hitler?", "opzioni": {"a": "Germania", "b": "Austria", "c": "Polonia", "d": "Svizzera"}, "risposta": "b", "categoria": "Storia", "difficolta": "Facile"},
    {"domanda": "Chi fu la regina d'Inghilterra dal 1952 al 2022?", "opzioni": {"a": "Vittoria", "b": "Elisabetta II", "c": "Maria I", "d": "Anna"}, "risposta": "b", "categoria": "Storia", "difficolta": "Facile"},
    {"domanda": "In quale città fu assassinato Giulio Cesare?", "opzioni": {"a": "Atene", "b": "Roma", "c": "Cartagine", "d": "Alessandria"}, "risposta": "b", "categoria": "Storia", "difficolta": "Facile"},
]

CATEGORIE = sorted({d["categoria"] for d in DOMANDE_ITALIANE})
DIFFICOLTA = ["Qualsiasi", "Facile", "Media", "Difficile"]
